### ISSUE TITLE
 remove mobileOverlay

### ISSUE THREAD

**Issue by X-OBJECT** [DJDoubleD/Qobuz-Mobile-Unlock#1]
In which line of script to change to remove mobileOverlay ?

**Comment by DJDoubleD** [comment]
> In which line of script to change to remove mobileOverlay ?

You don't need to change anything in the script.
Just install the script in any Tampermonkey supporting browser and it will automatically remove the mobileOverlay when visiting the Qobuz sites on smaller screens.
